### PR TITLE
UML feature bug fixes

### PR DESCRIPTION
**Pull request by hanstirtaputra**
## Changes made:
- Update UML connection to account for rotation, resizing, and unselecting elements. Note that the connection formed on a rotated UML element still has some quirks at certain rotation angles (the line might be a straight line instead) 
- Update unit test cases to remove some assertions

I think that I will work on a better solution (such as updating the connection anchor point as the UML element rotates) after working on other more important features (eg. deleting of connection lines).

### CODE REVIEW

**Review by ianyong — COMMENTED** [review]
Getting a huge delay between rotating/moving UML elements and the UML connections forming. Is this intended?

**Comment by hanstirtaputra** [comment]
> Getting a huge delay between rotating/moving UML elements and the UML connections forming. Is this intended?

We need to comment out `assert(checkRepresentation())` in `Graph.swift` to avoid this delay!

**Comment by ianyong** [comment]
> > Getting a huge delay between rotating/moving UML elements and the UML connections forming. Is this intended?
> 
> We need to comment out `assert(checkRepresentation())` in `Graph.swift` to avoid this delay!

Ah ok, thanks!

**Review by ianyong — APPROVED** [review]
LGTM! Just some quirks with the lines at certain angles as mentioned in the PR description.

simulator_screenshot_52881599-5BCA-4DDA-AD77-894C0BD4C04A

**Pull request merged**
